### ISSUE TITLE
AWS Cognito hosted UI signup error

### ISSUE THREAD

**Issue by 3k9** [the-realm-of-research/ror-issue#1]
When user clicks the signup button, the error message "An error was encountered with the requested page." appears with no further explication.

However the sign-in functionality works without problem.

**Comment by 3k9** [comment]
@charfole 新用户无法注册有可能是AWS Cognito服务的问题，因为我们用的是aws提供的一个UI。我们已经在aws反馈了这个问题，正在等待他们的回复

**Comment by charfole** [comment]
> @charfole 新用户无法注册有可能是AWS Cognito服务的问题，因为我们用的是aws提供的一个UI。我们已经在aws反馈了这个问题，正在等待他们的回复

明白，辛苦了😃

**Comment by 3k9** [comment]
@charfole 问题已经修复 :D bug的原因是因为每天需要发送的认证邮件超过了cognito的免费额度🤣，我们已经提高了额度，现在应该不会出现这个问题了
